# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gps_teste.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/gps_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QGroupBox {\n"
"        background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(255, 255, 255, 255));\n"
"        border: 1px solid gray;\n"
"        border-radius: 6px;\n"
"        border-width: 1px;\n"
"        margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"QTreeWidget {\n"
"        border: 1px white;\n"
"        border-radius: 6px;\n"
"        border-width: 1px;\n"
"        margin-top: 0.5em;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(290, 10, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.lbl_title.setFont(font)
        self.lbl_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_title.setAutoFillBackground(False)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.groupBox_config = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_config.setGeometry(QtCore.QRect(70, 410, 541, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_config.setFont(font)
        self.groupBox_config.setObjectName("groupBox_config")
        self.lbl_timer = QtWidgets.QLabel(self.groupBox_config)
        self.lbl_timer.setGeometry(QtCore.QRect(10, 65, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_timer.setFont(font)
        self.lbl_timer.setObjectName("lbl_timer")
        self.combo_port = QtWidgets.QComboBox(self.groupBox_config)
        self.combo_port.setGeometry(QtCore.QRect(200, 30, 201, 22))
        self.combo_port.setObjectName("combo_port")
        self.lbl_port = QtWidgets.QLabel(self.groupBox_config)
        self.lbl_port.setGeometry(QtCore.QRect(10, 30, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_port.setFont(font)
        self.lbl_port.setAutoFillBackground(False)
        self.lbl_port.setScaledContents(False)
        self.lbl_port.setObjectName("lbl_port")
        self.txt_timer = QtWidgets.QLineEdit(self.groupBox_config)
        self.txt_timer.setGeometry(QtCore.QRect(200, 65, 201, 20))
        self.txt_timer.setInputMask("")
        self.txt_timer.setText("")
        self.txt_timer.setObjectName("txt_timer")
        self.btn_apply = QtWidgets.QPushButton(self.groupBox_config)
        self.btn_apply.setGeometry(QtCore.QRect(410, 25, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_apply.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/icon_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_apply.setIcon(icon1)
        self.btn_apply.setObjectName("btn_apply")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 80, 700, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lbl_sattelite = QtWidgets.QLabel(self.groupBox)
        self.lbl_sattelite.setGeometry(QtCore.QRect(400, 150, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_sattelite.setFont(font)
        self.lbl_sattelite.setObjectName("lbl_sattelite")
        self.txt_date = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_date.setGeometry(QtCore.QRect(510, 90, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_date.setFont(font)
        self.txt_date.setReadOnly(True)
        self.txt_date.setPlainText("")
        self.txt_date.setObjectName("txt_date")
        self.lbl_altitude = QtWidgets.QLabel(self.groupBox)
        self.lbl_altitude.setGeometry(QtCore.QRect(30, 150, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_altitude.setFont(font)
        self.lbl_altitude.setObjectName("lbl_altitude")
        self.lbl_long = QtWidgets.QLabel(self.groupBox)
        self.lbl_long.setGeometry(QtCore.QRect(30, 90, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_long.setFont(font)
        self.lbl_long.setObjectName("lbl_long")
        self.lbl_time = QtWidgets.QLabel(self.groupBox)
        self.lbl_time.setGeometry(QtCore.QRect(400, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_time.setFont(font)
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_date = QtWidgets.QLabel(self.groupBox)
        self.lbl_date.setGeometry(QtCore.QRect(400, 90, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_date.setFont(font)
        self.lbl_date.setObjectName("lbl_date")
        self.txt_satellite = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_satellite.setGeometry(QtCore.QRect(510, 150, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_satellite.setFont(font)
        self.txt_satellite.setReadOnly(True)
        self.txt_satellite.setPlainText("")
        self.txt_satellite.setObjectName("txt_satellite")
        self.lbl_latitude = QtWidgets.QLabel(self.groupBox)
        self.lbl_latitude.setGeometry(QtCore.QRect(30, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_latitude.setFont(font)
        self.lbl_latitude.setObjectName("lbl_latitude")
        self.txt_longitude = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_longitude.setGeometry(QtCore.QRect(180, 90, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_longitude.setFont(font)
        self.txt_longitude.setReadOnly(True)
        self.txt_longitude.setPlainText("")
        self.txt_longitude.setOverwriteMode(False)
        self.txt_longitude.setObjectName("txt_longitude")
        self.txt_time = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_time.setGeometry(QtCore.QRect(510, 30, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_time.setFont(font)
        self.txt_time.setReadOnly(True)
        self.txt_time.setPlainText("")
        self.txt_time.setObjectName("txt_time")
        self.lbl_speed = QtWidgets.QLabel(self.groupBox)
        self.lbl_speed.setGeometry(QtCore.QRect(20, 210, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_speed.setFont(font)
        self.lbl_speed.setObjectName("lbl_speed")
        self.lbl_status = QtWidgets.QLabel(self.groupBox)
        self.lbl_status.setGeometry(QtCore.QRect(400, 210, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_status.setFont(font)
        self.lbl_status.setObjectName("lbl_status")
        self.txt_speed = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_speed.setGeometry(QtCore.QRect(180, 210, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_speed.setFont(font)
        self.txt_speed.setReadOnly(True)
        self.txt_speed.setPlainText("")
        self.txt_speed.setObjectName("txt_speed")
        self.txt_altitude = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_altitude.setGeometry(QtCore.QRect(180, 150, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_altitude.setFont(font)
        self.txt_altitude.setReadOnly(True)
        self.txt_altitude.setPlainText("")
        self.txt_altitude.setObjectName("txt_altitude")
        self.txt_latitude = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_latitude.setGeometry(QtCore.QRect(180, 30, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_latitude.setFont(font)
        self.txt_latitude.setReadOnly(False)
        self.txt_latitude.setPlainText("")
        self.txt_latitude.setOverwriteMode(True)
        self.txt_latitude.setCenterOnScroll(True)
        self.txt_latitude.setObjectName("txt_latitude")
        self.lbl_runtime = QtWidgets.QLabel(self.groupBox)
        self.lbl_runtime.setGeometry(QtCore.QRect(180, 270, 181, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_runtime.setFont(font)
        self.lbl_runtime.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_runtime.setObjectName("lbl_runtime")
        self.txt_runtime = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_runtime.setGeometry(QtCore.QRect(390, 270, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt_runtime.setFont(font)
        self.txt_runtime.setReadOnly(True)
        self.txt_runtime.setPlainText("")
        self.txt_runtime.setObjectName("txt_runtime")
        self.lbl_status_txt = QtWidgets.QLabel(self.groupBox)
        self.lbl_status_txt.setGeometry(QtCore.QRect(510, 210, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl_status_txt.setFont(font)
        self.lbl_status_txt.setText("")
        self.lbl_status_txt.setObjectName("lbl_status_txt")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(620, 410, 150, 120))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_stop = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setGeometry(QtCore.QRect(10, 70, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_stop.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/icon_parar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop.setIcon(icon2)
        self.btn_stop.setObjectName("btn_stop")
        self.btn_start = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_start.setEnabled(False)
        self.btn_start.setGeometry(QtCore.QRect(10, 20, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_start.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagens/icon_gps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_start.setIcon(icon3)
        self.btn_start.setObjectName("btn_start")
        self.groupBox.raise_()
        self.lbl_title.raise_()
        self.groupBox_config.raise_()
        self.groupBox_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EREDATRAVEA"))
        self.lbl_title.setText(_translate("MainWindow", "EREDATRAVEA"))
        self.groupBox_config.setTitle(_translate("MainWindow", "Configurações"))
        self.lbl_timer.setText(_translate("MainWindow", "Tempo de Aquisição[min]:"))
        self.lbl_port.setText(_translate("MainWindow", "Selecione a porta serial:"))
        self.txt_timer.setPlaceholderText(_translate("MainWindow", "Padrão: 1, Mínimo: 1, Máximo: 7600"))
        self.btn_apply.setText(_translate("MainWindow", "Conectar"))
        self.groupBox.setTitle(_translate("MainWindow", "Informações"))
        self.lbl_sattelite.setText(_translate("MainWindow", "Satélites:"))
        self.lbl_altitude.setText(_translate("MainWindow", "Altitude[m]:"))
        self.lbl_long.setText(_translate("MainWindow", "Longitude:"))
        self.lbl_time.setText(_translate("MainWindow", "Hora:"))
        self.lbl_date.setText(_translate("MainWindow", "Data:"))
        self.lbl_latitude.setText(_translate("MainWindow", "Latitude:"))
        self.lbl_speed.setText(_translate("MainWindow", "Velocidade[km/h]:"))
        self.lbl_status.setText(_translate("MainWindow", "Status:"))
        self.lbl_runtime.setText(_translate("MainWindow", "Tempo de Execução:"))
        self.btn_stop.setText(_translate("MainWindow", "Finalizar"))
        self.btn_start.setText(_translate("MainWindow", "Iniciar"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


import resources_rc
